import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Navibar } from '@/components'
import { ThemeModeScript } from "flowbite-react"
import { Flowbite } from "flowbite-react";
import { AppProvider } from '@/context/appContext';

import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config'
import Web3ModalProvider from '@/context/wagmiContext'


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
        <head>
          <ThemeModeScript />
        </head>
        <Flowbite>
        <Web3ModalProvider initialState={initialState}>
          <AppProvider>
            
              <body className={"bg-slate-50 dark:bg-black text-black dark:text-white"}>
                <Navibar/>
                {children}
              </body>
            
          </AppProvider>
        </Web3ModalProvider>
          
        </Flowbite>

    </html>
  )
}
